cosmos-installer: null
# Configuration for ComposeToolbox setup

# Name of the big-bear-composetoolbox application
name: big-bear-composetoolbox
# Service definitions for the big-bear-composetoolbox application
services:
  # Service name: big-bear-composetoolbox
  # The `big-bear-composetoolbox` service definition
  big-bear-composetoolbox:
    # Environment variables
    environment:
      # Node environment
      NODE_ENV: production
    # Image to be used for the container
    image: ghcr.io/bluegoosemedia/composetoolbox:latest
    pull_policy: always
    # Ports mapping between host and container
    ports:
      - "3002:3000"
    # Container restart policy
    restart: unless-stopped
    # Volumes to be mounted to the container
    volumes:
      - big-bear-composetoolbox_data:/app/data
    # Name of the container
    container_name: "big-bear-composetoolbox"
volumes:
  big-bear-composetoolbox_data:
    name: big-bear-composetoolbox_data
    driver: local
minVersion: 0.14.0
