cosmos-installer: null
services:
  chromium:
    container_name: big-bear-chromium # Name of the Docker container
    image: linuxserver/chromium:version-6ae43f81 # Docker image for the chromium browser
    ports:
      - "3000:3000" # Expose port 3000 for HTTP VNC access
      - "3001:3001" # Expose port 3001 for HTTPS VNC access
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - CHROME_CLI=https://community.bigbeartechworld.com/ # Set the default URL to Big Bear Tech World
    shm_size: 1gb # Allocate 1 GB of shared memory
    volumes:
      - big-bear-chromium_config:/config # Mount the config directory for persistent data
volumes:
  big-bear-chromium_config:
    name: big-bear-chromium_config
    driver: local
minVersion: 0.14.0
