cosmos-installer: null
# Docker Compose configuration for BigBear CasaOS JFA-GO
# This service provides a web interface for managing Jellyfin users and permissions
# Initial Version: latest

# Name of the big-bear-jfa-go application
# Service definitions for the big-bear-jfa-go application
services:
  # Main service configuration for the JFA-GO application
  # This service provides a web interface running on port 8056 for user administration
  big-bear-jfa-go:
    # Name of the container
    container_name: big-bear-jfa-go
    # Image to be used for the container specifies the hrfee/jfa-go version and source
    image: hrfee/jfa-go:latest
    # Container restart policy - restarts the container unless manually stopped
    restart: unless-stopped
    # Volume mappings required for system integration
    # These mounts allow the container to interact with the host system
    volumes:
      - big-bear-jfa-go_.config_jfa-go:/data # Path to wherever you want to store the config file and other data
      - big-bear-jfa-go_jellyfin:/jf # Only needed for password resets through Jellyfin, ignore if not using or using Emby
      - /etc/localtime:/etc/localtime:ro # Makes sure time is correct
    # Map port 8056 on the host to port 8056 on the container
    ports:
      - "8056:8056"
volumes:
  big-bear-jfa-go_.config_jfa-go:
    name: big-bear-jfa-go_.config_jfa-go
    driver: local
  big-bear-jfa-go_jellyfin:
    name: big-bear-jfa-go_jellyfin
    driver: local
minVersion: 0.14.0
