cosmos-installer: null
name: big-bear-spoolman # Name of the compose project
services:
  app:
    image: ghcr.io/donkie/spoolman:0.22.1 # Image to use for the spoolman service
    ports:
      - "7912:8000" # Maps port 7912 on the host to port 8000 on the container
    volumes:
      - big-bear-spoolman_data:/home/app/.local/share/spoolman # Binds a volume from host to container for data storage
    environment:
      - TZ=$TZ # Sets the timezone, using host's timezone variable
      - SPOOLMAN_DB_TYPE=sqlite # Database type (sqlite, mysql, postgres, cockroachdb)
      - SPOOLMAN_LOGGING_LEVEL=INFO # Logging level (DEBUG, INFO, WARNING, ERROR, CRITICAL)
      - SPOOLMAN_AUTOMATIC_BACKUP=TRUE # Enable automatic nightly backups for SQLite
    restart: unless-stopped # Service will restart unless it is explicitly stopped
    network_mode: bridge # Uses bridge network mode
volumes:
  big-bear-spoolman_data:
    name: big-bear-spoolman_data
    driver: local
minVersion: 0.14.0
